# https://github.com/zetanumbers/nushell/blob/main/docker/cross-rs/aarch64-unknown-linux-gnu.dockerfile
# https://github.com/cross-rs/cross/wiki/Configuration
# sudo apt-get install pkg-config libssl-dev
# sudo apt-get install -y autoconf automake libtool git
# docker build -f ./Dockerfile_aarch64-2 -t  rust-aarch64:1.0.0 .
# docker run -it 9bdc83058fd1    /bin/bash
FROM aam-rust-aarch64:1.0 AS build
COPY bin/protoc /usr/local/bin/protoc
RUN chmod +x /usr/local/bin/protoc