# https://github.com/zetanumbers/nushell/blob/main/docker/cross-rs/aarch64-unknown-linux-gnu.dockerfile
# https://github.com/cross-rs/cross/wiki/Configuration
# sudo apt-get install pkg-config libssl-dev
# sudo apt-get install -y autoconf automake libtool git
# docker build -f ./Dockerfile -t  aam-rust-aarch64:1.0.0 .
# docker run -it a0d6c026230a  -v /tool/toolchain/buildroot-rk3308:/tool/toolchain/buildroot-rk3308 /bin/bash

FROM registry.cn-hangzhou.aliyuncs.com/alvisisme/ubuntu:20.04 AS cross-base
RUN apt-get update
RUN apt-get install --assume-yes --no-install-recommends \
    autoconf \
    automake \
    binutils \
    ca-certificates \
    curl \
    file \
    gcc \
    git \
    sudo \
    wget \
    libtool \
    m4 \
    g++ \
    gfortran \
    libc6-dev \
    apt-utils \
    libclang-dev \
    libevdev-dev \
    libssl-dev \
    make \ 
    pkg-config

COPY protoc/bin/protoc /usr/bin/protoc
RUN chmod +x /usr/local/bin/protoc

RUN export RUSTUP_DIST_SERVER=https://rsproxy.cn
RUN export RUSTUP_UPDATE_ROOT=https://rsproxy.cn/rustup

RUN curl https://sh.rustup.rs -sSf > /tmp/rustup-init.sh \
    && chmod +x /tmp/rustup-init.sh \
    && sh /tmp/rustup-init.sh -y \
    && rm -rf /tmp/rustup-init.sh

RUN PATH="~/.cargo/bin:${PATH}" 
ENV PATH "$PATH:~/.cargo/bin" 
RUN ~/.cargo/bin/cargo search 
RUN ~/.cargo/bin/rustc --version


FROM cross-base AS build

RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    g++-aarch64-linux-gnu \
    gfortran-aarch64-linux-gnu \
    libc6-dev-arm64-cross

RUN ln -s /lib/x86_64-linux-gnu/libmpfr.so.6.0.2 /lib/x86_64-linux-gnu/libmpfr.so.4